# repos:
#   # 1. Sort imports
#   - repo: https://github.com/pycqa/isort
#     rev: 6.0.1
#     hooks:
#       - id: isort
#         language: system         
#         files: \.py$
#         additional_dependencies: []

#   # 2. Format with black
#   - repo: https://github.com/psf/black
#     rev: 24.4.2
#     hooks:
#       - id: black
#         language: system         

  # # 3. Lint with flake8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.2.0
  #   hooks:
  #     - id: flake8
  #       language: system

  # # 4. Static typing with mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       language: system
  #       additional_dependencies: []  # Add e.g. ["pydantic"] if needed
